# Generated by Django 5.2.8 on 2025-11-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите полное название книги",
                        max_length=255,
                        verbose_name="Название книги",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        help_text="ФИО автора книги",
                        max_length=255,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Краткое описание содержания книги",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        help_text="Международный стандартный номер книги (13 цифр)",
                        max_length=13,
                        unique=True,
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "year_published",
                    models.IntegerField(
                        help_text="Год, когда была опубликована книга",
                        verbose_name="Год издания",
                    ),
                ),
                (
                    "pages",
                    models.IntegerField(
                        help_text="Общее количество страниц в книге",
                        verbose_name="Количество страниц",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение обложки книги",
                        null=True,
                        upload_to="books/covers/",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок новости",
                        max_length=255,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Полный текст новости", verbose_name="Содержание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Иллюстрация к новости",
                        null=True,
                        upload_to="news/images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, чтобы новость была видна всем пользователям",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Элемент", "verbose_name_plural": "Элементы"},
        ),
    ]
